export enum RoleEnum {
  RENTER = "RENTER",
  LISTER = "LISTER",
}

export enum ProviderEnum {
  EMAIL = "EMAIL",
  GOOGLE = "GOOGLE",
  FACEBOOK = "FACEBOOK",
  LINKEDIN = "LINKEDIN",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
}

export enum PropertyStatus {
  PENDING_REVIEW = "PENDING_REVIEW",
  ACTIVE = "ACTIVE",
  RENTED = "RENTED",
  INACTIVE = "INACTIVE",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
  PENDING_BOOKING = "PENDING_BOOKING",
}

export enum PropertyListingType {
  RENT = "RENT",
  LEASE = "LEASE",
  SALE = "SALE",
}

export enum PropertyType {
  BUNGALOW = "BUNGALOW",
  TWO_STORY = "TWO_STORY",
  THREE_STORY = "THREE_STORY",
  FOUR_STORY = "FOUR_STORY",
  SIX_PLUS_STORY = "SIX_PLUS_STORY",
  APARTMENT = "APARTMENT",
  DUPLEX = "DUPLEX",
  MANSION = "MANSION",
}

export enum RoomType {
  STUDIO = "STUDIO",
  ONE_BEDROOM = "ONE_BEDROOM",
  TWO_BEDROOM = "TWO_BEDROOM",
  THREE_BEDROOM = "THREE_BEDROOM",
  FOUR_BEDROOM = "FOUR_BEDROOM",
  FIVE_PLUS_BEDROOM = "FIVE_PLUS_BEDROOM",
  SELF_CONTAIN = "SELF_CONTAIN",
}

export enum RentalPeriod {
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
}

export enum DayOfWeek {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

export enum DocumentType {
  NIN = "NIN",
  DRIVERS_LICENSE = "DRIVERS_LICENSE",
  INTERNATIONAL_PASSPORT = "INTERNATIONAL_PASSPORT",
}

export enum VerificationStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum TokenType {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
}

export enum TransactionType {
  PREMIUM_LISTING = "PREMIUM_LISTING",
  BASIC_LISTING = "BASIC_LISTING",
  FEATURED_LISTING = "FEATURED_LISTING",
  AD_PLACEMENT = "AD_PLACEMENT",
  API_ACCESS = "API_ACCESS",
  SUBSCRIPTION = "SUBSCRIPTION",
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  ESCROW_RELEASE = "ESCROW_RELEASE",
  ESCROW_HOLD = "ESCROW_HOLD",
  ESCROW_REFUND = "ESCROW_REFUND",
  REFUND = "REFUND",
  RENT_PAYMENT = "RENT_PAYMENT",
  PLATFORM_FEE = "PLATFORM_FEE",
}

export enum TransactionStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
  HELD = "HELD",
  RELEASED = "RELEASED",
}

export enum PaymentGateway {
  PAYSTACK = "PAYSTACK",
  FLUTTERWAVE = "FLUTTERWAVE",
  STRIPE = "STRIPE",
  PAYPAL = "PAYPAL",
}

export enum RefundStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PROCESSED = "PROCESSED",
}

export enum WalletTransactionType {
  RENT_PAYMENT = "RENT_PAYMENT",
  WITHDRAWAL = "WITHDRAWAL",
  DEPOSIT = "DEPOSIT",
  REFUND = "REFUND",
  ESCROW_RELEASE = "ESCROW_RELEASE",
  PLATFORM_FEE = "PLATFORM_FEE",
}

export enum AdPosition {
  HEADER_BANNER = "HEADER_BANNER",
  SIDEBAR_TOP = "SIDEBAR_TOP",
  SIDEBAR_BOTTOM = "SIDEBAR_BOTTOM",
  CONTENT_TOP = "CONTENT_TOP",
  CONTENT_MIDDLE = "CONTENT_MIDDLE",
  CONTENT_BOTTOM = "CONTENT_BOTTOM",
  FOOTER = "FOOTER",
  POPUP = "POPUP",
  FLOATING = "FLOATING",
}

export enum AdType {
  STANDARD = "STANDARD",
  PREMIUM = "PREMIUM",
  SPONSORED = "SPONSORED",
}

export enum AdStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ACTIVE = "ACTIVE",
  PAUSED = "PAUSED",
  EXPIRED = "EXPIRED",
}

export enum AuditAction {
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  SUSPEND = "SUSPEND",
  ACTIVATE = "ACTIVATE",
  EXPORT = "EXPORT",
}

export enum ContentType {
  PAGE = "PAGE",
  POLICY = "POLICY",
  TERMS = "TERMS",
  FAQ = "FAQ",
  HELP = "HELP",
  LANDING = "LANDING",
}

export enum ContentStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum MessageType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  DOCUMENT = "DOCUMENT",
  SYSTEM = "SYSTEM",
}

export enum NotificationType {
  PROPERTY_APPROVED = "PROPERTY_APPROVED",
  PROPERTY_REJECTED = "PROPERTY_REJECTED",
  NEW_MESSAGE = "NEW_MESSAGE",
  PROPERTY_LIKED = "PROPERTY_LIKED",
  PROPERTY_VIEWED = "PROPERTY_VIEWED",
  VERIFICATION_APPROVED = "VERIFICATION_APPROVED",
  VERIFICATION_REJECTED = "VERIFICATION_REJECTED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED",
  PROPERTY_INQUIRY = "PROPERTY_INQUIRY",
  SYSTEM_UPDATE = "SYSTEM_UPDATE",
  BOOKING_CREATED = "BOOKING_CREATED",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  ESCROW_RELEASED = "ESCROW_RELEASED",
  SYSTEM_AUTO_RELEASE = "SYSTEM_AUTO_RELEASE",
  DISPUTE_CREATED = "DISPUTE_CREATED",
  DISPUTE_RESOLVED = "DISPUTE_RESOLVED",
  REFUND_CREATED = "REFUND_CREATED",
  REFUND_APPROVED = "REFUND_APPROVED",
  REFUND_REJECTED = "REFUND_REJECTED",
  REFUND_PROCESSED = "REFUND_PROCESSED",
  WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED",
  WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED",
}

export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  DISPUTED = "DISPUTED",
}

export enum DisputeStatus {
  PENDING = "PENDING",
  IN_REVIEW = "IN_REVIEW",
  RESOLVED = "RESOLVED",
  REJECTED = "REJECTED",
}
